digraph G {
n2[label="all", color="red"];
n10[label="data/processed/test_df.csv", color="red"];
n6[label="data/processed/train_df.csv", color="red"];
n7[label="data/raw/audio_audio_features.csv", color="red"];
n4[label="doc/spotify-track-predictor-report.Rmd", color="green"];
n3[label="doc/spotify-track-predictor-report.md", color="red"];
n9[label="results/best_hyperparameters.csv", color="red"];
n11[label="results/cv_df.csv", color="red"];
n5[label="results/paired_distribution_and_correlation.png", color="red"];
n8[label="results/predict_vs_test.png", color="red"];
n3 -> n2 ; 
n7 -> n10 ; 
n7 -> n6 ; 
n4 -> n3 ; 
n9 -> n3 ; 
n11 -> n3 ; 
n5 -> n3 ; 
n8 -> n3 ; 
n10 -> n9 ; 
n6 -> n9 ; 
n10 -> n11 ; 
n6 -> n11 ; 
n6 -> n5 ; 
n6 -> n8 ; 
}
